services:
  database:
    image: "postgres" # use latest official postgres version
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    container_name: postgres-db
    env_file:
      - database/.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    command: -p 5432
    mem_limit: 3G
volumes:
  database-data: #
